apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: alert-fyllut-ettersending
  namespace: skjemadigitalisering
  labels:
    team: skjemadigitalisering
spec:
  receivers:
    slack:
      channel: "#fyllut-alerts-prod"
      prependText: "<!here>"
  alerts:
    - alert: høy feilrate i logger
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="fyllut-ettersending",log_level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="skjemabygging-formio"}[3m]))) > 10
      for: 3m
      action: "Sjekk loggene til app {{ $labels.log_app }} i Kibana: https://logs.adeo.no/goto/b7870aa0-33f8-11ed-b3e8-d969437dd878"
    - alert: https://fyllut-ettersending.dev.intern.nav.no unavailable
      expr: kube_deployment_status_replicas_available{deployment="fyllut-ettersending"} == 0
      for: 1m
      action: "Sjekk loggene til app {{ $labels.log_app }} i Kibana: https://logs.adeo.no/goto/b7870aa0-33f8-11ed-b3e8-d969437dd878"
      sla: respond within 1h, during office hours
      severity: danger
