env-name: dev-gcp
logs-url: https://logs.adeo.no/app/r/s/1n4vb
special-type-to-use-in-alertmanager-config: 'fyllut-sendinn-alerts-dev'
ingresses:
  - 'https://fyllut-ettersending.intern.dev.nav.no/fyllut-ettersending'
accessPolicy:
  outbound:
    rules:
      - application: skjemautfylling
      - application: skjemautfylling-experimental
      - application: skjemautfylling-delingslenke
      - application: skjemautfylling-preprod
env:
  - name: FYLLUT_BASE_URL
    value: http://skjemautfylling-preprod/fyllut
  - name: INNSENDING_API_AUDIENCE
    value: 'dev-gcp:team-soknad:innsending-api'
  - name: INNSENDING_API_URL
    value: 'http://innsending-api.team-soknad'
  - name: MIN_SIDE_FRONTEND_URL
    value: 'https://www.intern.dev.nav.no/minside'
  - name: APP_ENV
    value: development
