ingresses:
- "https://fyllut-ettersending.dev.intern.nav.no/fyllut-ettersending"
accessPolicy:
  outbound:
    rules:
      - application: skjemautfylling
      - application: skjemautfylling-experimental
      - application: skjemautfylling-delingslenke
env:
  - name: FYLLUT_BASE_URL
    value: http://skjemautfylling/fyllut
