apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "fyllut-ettersending"
  namespace: "skjemadigitalisering"
  labels:
    team: skjemadigitalisering
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{image}}
  port: 3002
  liveness:
    path: "/fyllut-ettersending/api/internal/isalive"
    port: 3002
    initialDelay: 20
    timeout: 10
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: "/fyllut-ettersending/api/internal/isready"
    port: 3002
    initialDelay: 20
    timeout: 10
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: false
      level: Level4
  resources:
    requests:
      memory: 512Mi
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  accessPolicy:
    outbound:
      rules:
      {{#each accessPolicy.outbound.rules}}
        - application: {{this.application}}
      {{/each}}
        - application: nav-dekoratoren
          namespace: personbruker
        - application: innsending-api
          namespace: team-soknad
  env:
  {{#each env}}
    - name: {{this.name}}
      value: {{this.value}}
  {{/each}}