apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "fyllut-ettersending"
  namespace: "skjemadigitalisering"
  labels:
    team: skjemadigitalisering
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/api/internal/isalive"
    port: 3000
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/api/internal/isready"
    port: 3000
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  accessPolicy:
    outbound:
      rules:
      {{#each accessPolicy.outbound.rules}}
        - application: {{this.application}}
      {{/each}}
  env:
  {{#each env}}
    - name: {{this.name}}
      value: {{this.value}}
  {{/each}}
