apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "fyllut-ettersending"
  namespace: "skjemadigitalisering"
  labels:
    team: skjemadigitalisering
  annotations:
    texas.nais.io/enabled: "true"
spec:
  image: {{image}}
  port: 3002
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  liveness:
    path: "/fyllut-ettersending/api/internal/isalive"
    port: 3002
    initialDelay: 20
    timeout: 10
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: "/fyllut-ettersending/api/internal/isready"
    port: 3002
    initialDelay: 20
    timeout: 10
  prometheus:
    enabled: false
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: false
      level: Level4
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  accessPolicy:
    outbound:
      rules:
      {{#each accessPolicy.outbound.rules}}
        - application: {{this.application}}
      {{/each}}
        - application: nav-dekoratoren
          namespace: personbruker
        - application: innsending-api
          namespace: team-soknad
  env:
    - name: LOG_LINK
      value: {{logs-url}}
  {{#each env}}
    - name: {{this.name}}
      value: {{this.value}}
  {{/each}}
