env-name: prod-gcp
logs-url: https://logs.adeo.no/app/r/s/joMHK
special-type-to-use-in-alertmanager-config: "fyllut-sendinn-alerts"
ingresses:
  - "https://www.nav.no/fyllut-ettersending"
accessPolicy:
  outbound:
    rules:
      - application: skjemautfylling
    external:
      - host: www.nav.no
env:
  - name: FYLLUT_BASE_URL
    value: http://skjemautfylling/fyllut
