ingresses:
  - "https://www.nav.no/fyllut-ettersending"
accessPolicy:
  outbound:
    rules:
      - application: skjemautfylling
env:
  - name: FYLLUT_BASE_URL
    value: http://skjemautfylling/fyllut
