env-name: prod-gcp
logs-url: https://logs.adeo.no/app/r/s/joMHK
special-type-to-use-in-alertmanager-config: "fyllut-sendinn-alerts"
ingresses:
  - "https://www.nav.no/fyllut-ettersending"
accessPolicy:
  outbound:
    rules:
      - application: skjemautfylling
      - application: innsending-api
env:
  - name: FYLLUT_BASE_URL
    value: http://skjemautfylling/fyllut
  - name: INNSENDING_API_AUDIENCE
    value: "prod-gcp:team-soknad:innsending-api"
  - name: INNSENDING_API_URL
    value: "http://innsending-api.team-soknad"
  - name: SEND_INN_FRONTEND_URL
    value: "https://www.nav.no/sendinn"
  - name: MIN_SIDE_URL
    value: "https://www.nav.no/minside"