name: Deploy alerts to NAIS
on:
  push:
    branches:
      - main
    paths:
      - '.nais/alerts.yaml'
      - '.nais/dev.yaml'
      - '.nais/prod.yaml'
      - '.github/workflows/alert-deploy.yaml'
jobs:
  apply-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/alerts.yaml
          VARS: .nais/dev.yaml
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerts.yaml
          VARS: .nais/prod.yaml
