name: Cypress Tests

on:
  push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.17.1"
      - name: "Bootstrap"
        run: yarn bootstrap
      - name: "Cypress tests"
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: yarn run start
          wait-on: "http://localhost:3002, http://localhost:3002/internal/isready"
          config: video=false