name: "Build and deploy (dev) fyllut-ettersending"
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**/**.md"

jobs:
  test:
    name: "Test"
    uses: ./.github/workflows/test.yaml

  build:
    name: "Build"
    uses: ./.github/workflows/build-push.yaml
    with:
      environment: dev
    secrets: inherit

  deployAppToDev:
    name: "Deploy app to dev"
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Deploy to DEV"
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/dev.yaml
