name: "Build and deploy (prod) fyllut-ettersending"
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**/**.md"

jobs:
  test:
    name: "Test"
    uses: ./.github/workflows/test.yaml

  build-and-push:
    name: "Build"
    uses: ./.github/workflows/build-push.yaml
    with:
      environment: prod
    secrets: inherit
    permissions:
      contents: "read"
      id-token: "write"
      packages: "read"

  deployAppToProd:
    name: "Deploy app to prod"
    needs: [build-and-push, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Deploy to PROD"
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/prod.yaml
          VAR: image=${{ needs.build-and-push.outputs.image }}
