name: Manually triggered deployment
run-name: Manual deploy to ${{ inputs.environment }} [${{ github.ref_name }}]
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  test:
    name: 'Test'
    uses: ./.github/workflows/test.yaml

  build-and-push:
    name: 'Build and push'
    uses: ./.github/workflows/build-push.yaml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'read'

  deployAppToProd:
    name: 'Deploy app to prod'
    needs: [build-and-push, test]
    if: github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: 'Deploy to PROD'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/prod.yaml
          VAR: image=${{ needs.build-and-push.outputs.image }}

  deployAppToDev:
    name: 'Deploy app to dev'
    needs: [build-and-push, test]
    if: github.event.inputs.environment == 'dev'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: 'Deploy to DEV'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/dev.yaml
          VAR: image=${{ needs.build-and-push.outputs.image }}
