name: "Test"
on: push

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.1"
      - name: "install dependencies"
        run: yarn install --frozen-lockfile
      - name: "Build application"
        run: yarn build:mock
      - name: "Cypress tests"
        uses: cypress-io/github-action@v4
        with:
          env: "NEXT_PUBLIC_SENDINN_URL=https://www.test.no/sendinn/opprettSoknadResource"
          install: false
          start: "yarn run start:mock"
          wait-on: "http://localhost:3002/fyllut-ettersending, http://localhost:3002/fyllut-ettersending/api/internal/isready"
          config-file: "cypress.config.ts"
