name: "Test"
run-name: "Test [${{ github.event_name }}]"
on: 
  workflow_call:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**.md'
      - '**/**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**/**.md'

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"
      - name: "install dependencies"
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build application"
        run: yarn build:test
      - name: "Cypress tests"
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: "yarn run start:with:test"
          wait-on: "http://localhost:3002/fyllut-ettersending, http://localhost:3002/fyllut-ettersending/api/internal/isready"
          config-file: "cypress.config.ts"
