name: 'Test'
run-name: 'Test [${{ github.event_name }}]'
on:
  workflow_call:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**.md'
      - '**/**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**/**.md'

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'
      - name: 'install dependencies'
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set environment variables
        run: cp .env.test .env
      - name: 'Build application'
        run: yarn build
      - name: 'Run mock server'
        run: yarn mocks:no-cli &
      - name: 'Cypress tests'
        uses: cypress-io/github-action@v6
        with:
          install: false
          start: 'yarn start'
          wait-on: 'http://localhost:3002/fyllut-ettersending, http://localhost:3002/fyllut-ettersending/api/internal/isready'
          config-file: 'cypress.config.ts'
